// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanSu.Data;

namespace QuanLyNhanSu.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20191130023121_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanLyNhanSu.Models.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiemNhanVien");

                    b.Property<string>("MaNV");

                    b.Property<DateTime>("NgayLamViec");

                    b.Property<int?>("NhanVienId");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("QuanLyNhanSu.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Luong");

                    b.Property<string>("MaNV");

                    b.Property<string>("MaPB");

                    b.Property<int?>("PhongBanId");

                    b.Property<string>("TenNV");

                    b.HasKey("Id");

                    b.HasIndex("PhongBanId");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Models.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaPB");

                    b.Property<string>("TenPB");

                    b.HasKey("Id");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaPB");

                    b.Property<string>("MatKhau");

                    b.Property<int?>("PhongBanId");

                    b.Property<string>("TenDangNhap");

                    b.HasKey("Id");

                    b.HasIndex("PhongBanId");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Models.ChamCong", b =>
                {
                    b.HasOne("QuanLyNhanSu.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId");
                });

            modelBuilder.Entity("QuanLyNhanSu.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyNhanSu.Models.PhongBan", "PhongBan")
                        .WithMany("NhanVien")
                        .HasForeignKey("PhongBanId");
                });

            modelBuilder.Entity("QuanLyNhanSu.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyNhanSu.Models.PhongBan", "PhongBan")
                        .WithMany("TaiKhoan")
                        .HasForeignKey("PhongBanId");
                });
#pragma warning restore 612, 618
        }
    }
}
